import { SiteHeader } from '@/components/header/SiteHeader';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ComponentClipboardProvider } from '@/lib/store/component-clipboard-context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
              <ComponentClipboardProvider>
                <SiteHeader/>
                {children}
              </ComponentClipboardProvider>
            </body>
        </html>
    );
}
